 


const data = {
  products: [
    {
      _id: '2',
      name: ' black Dog',
      image: '/img/2.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: ' A nice black Dog',
    },
    {
      _id: '3',
      name: 'Dog',
      image: '/img/3.jpg',
      price: 110,
      countInStock: 14,
      rating: 4.5,
      numReviews: 11,
      description: 'A nice Dog',
    },
    {
      _id: '4',
      name: 'Falcon',
      image: '/img/4.jpg',
      price: 320,
      countInStock: 1,
      rating: 4.5,
      numReviews: 15,
      description: 'A good Falcon',
    },
    {
      _id: '5',
      name: ' A beautiful Cat',
      image: '/img/5.jpg',
      price: 400,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: ' A beautiful Cat',
    },
    {
      _id: '6',
      name: 'Sheep',
      image: '/img/6.jpg',
      price: 3000,
      countInStock: 9,
      rating: 9.5,
      numReviews: 9,
      description: 'high quality Sheep',
    },
    {
      _id: '7',
      name: 'Duck',
      image: '/img/7.jpg',
      price: 1200,
      countInStock: 10,
      rating: 3.5,
      numReviews: 19,
      description: 'high quality Duck',
    },
    {
      _id: '8',
      name: 'Peacock',
      image: '/img/8.jpg',
      price: 1020,
      countInStock: 10,
      rating: 4.1,
      numReviews: 10,
      description: 'high quality Peacock',
    },
    {
      _id: '9',
      name: 'Peafowl',
      image: '/img/9.jpg',
      price: 1111,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
      description: 'high quality Peafowl',
    },
    {
      _id: '10',
      name: 'Dog',
      image: '/img/10.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.9,
      numReviews: 10,
      description: 'high quality dog',
    },
    {
      _id: '11',
      name: 'Cats',
      image: '/img/11.jpg',
      price: 2000,
      countInStock: 8,
      rating: 4.8,
      numReviews: 10,
      description: 'high quality Cats',
    },
    {
      _id: '12',
      name: 'Dog',
      image: '/img/12.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dog',
    },

  ]
}
export default data;