const cats = [
  {
    id: 1,
    src: "/img/cat-1.jpg",
    title:
    " Cats need a well-balanced, meat-based diet to stay fit and healthy - they cannot be vegetarian. Make sure your cat eats a balanced diet  that is suitable for their age, health status and lifestyle. Why not try our cat food?" ,
    alt: "What the healty diet for a Cat ?",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 2,
    src: "/img/cat-2.jpg",
    title:
      " Cat trees come in about as many varieties as, well, actual trees. ... Cat trees also give your cat a space that is completely their own. The best cat trees promote exercise, giving your kitty a safe place to leap, climb, scratch, jump and play—one that's not your furniture, counters or cabinetry",
    alt: "Do cats actually use cat trees?",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 3,
    src: "/img/cat-3.jpg",
    title:   " Cats sometimes run away and go missing, and sometimes they return home. They can be gone for several days or disappear entirely. For a cat guardian, this is an emotional and upsetting experience",
    alt: "Do cats come back home after they run away?",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 4,
    src: "/img/cat-4.jpg",
    title:   "If you thought cats spent a lot of their lives sleeping, you’d be right. According to Veterinary Hub, Cats actually spend 70% of their lives sleeping, which works out to around 13-16 hours a day. It’s a cat’s life!.",
    alt: "Cats spend 70% of their lives sleeping",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 5,
    src: "/img/cat-5.jpg",
    title:   "If you thought cats spent a lot of their lives sleeping, you’d be right. According to Veterinary Hub, Cats actually spend 70% of their lives sleeping, which works out to around 13-16 hours a day. It’s a cat’s life! ",
    alt: "Cats spend 70% of their lives sleeping",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 6,
    src: "/img/cat-6.jpg",
    title:   " Angry, aggressive: Ears back, pupils very constricted and their tail may be up or down with the fur standing on end—an aggressive cat will stare down another cat and growl or yowl until the other cat gives way.",
    alt: "What do cats do when angry?",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 7,
    src: "/img/cat-7.jpg",
    title:   " Remember, while it's totally normal for your cat to get annoyed with you from time to time (you are roommates/best friends/confidants, after all), if it's happening frequently then it's good to do some sleuthing and try to get to the bottom of why they're feeling this way often.",
    alt: "Do cats get angry at their owners?",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 8,
    src: "/img/cat-8.jpg",
    title:   " remember, while it's totally normal for your cat to get annoyed with you from time to time (you are roommates/best friends/confidants, after all), if it's happening frequently then it's good to do some sleuthing and try to get to the bottom of why they're feeling this way often.",
    alt: "Do cats get angry at their owners?",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 9,
    src: "/img/cat-9.jpg",
    title:   "lorem standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    alt: "Cat",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
  {
    id: 10,
    src: "/img/cat-10.jpg",
    title:   "lorem standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    alt: "Cat",
    link:"For More Information Click Here",
    class: "cats-info ",
  },
];
export default cats;
